// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchedulingTaskKind } from "../SchedulingTaskKind";

/**
 * ATA: delete one scheduling task (cron job, monitor, or loop) from a
 * thread's registry. Used by the `/scheduling` TUI panel's `d` shortcut.
 * Server aborts the task first if it's still running. Response is empty;
 * the panel observes the removal via the next `SchedulingTasksSnapshot`
 * notification, which the server emits immediately after the delete.
 */
export type SchedulingTaskDeleteParams = { threadId: string, taskId: string, kind: SchedulingTaskKind, };
