// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchedulingTasksSnapshotEvent } from "../SchedulingTasksSnapshotEvent";

export type SchedulingTasksSnapshotNotification = { threadId: string, event: SchedulingTasksSnapshotEvent, };
