// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchedulingMonitorOutputDeltaEvent } from "../SchedulingMonitorOutputDeltaEvent";

/**
 * Streamed line of output from a running monitor. The TUI renders this for
 * the user only; the LLM never sees it. See
 * `codex_protocol::protocol::SchedulingMonitorOutputDeltaEvent`.
 */
export type SchedulingMonitorOutputDeltaNotification = { threadId: string, event: SchedulingMonitorOutputDeltaEvent, };
