// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateDocumentSectionEvent } from "../UpdateDocumentSectionEvent";

export type UpdateDocumentSectionNotification = { threadId: string, event: UpdateDocumentSectionEvent, };
