// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when the agent calls `add_document_section`.
 */
export type AddDocumentSectionEvent = { call_id: string, turn_id: string, document_id: string, 
/**
 * Insert the new section AFTER this 0-based index. -1 for beginning.
 */
after_section_index: number, heading: string, content: string, 
/**
 * Whether the new section should be collapsible.
 */
foldable: boolean, 
/**
 * Short summary shown when the fold is collapsed.
 */
summary: string | null, };
