// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when the agent calls `append_to_section`.
 */
export type AppendDocumentSectionEvent = { call_id: string, turn_id: string, document_id: string, section_index: number, content: string, 
/**
 * Whether the appended content should be collapsible.
 */
foldable: boolean, 
/**
 * Short summary shown when the fold is collapsed.
 */
summary: string | null, };
