// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentItem = { "type": "input_text", text: string, } | { "type": "input_image", image_url: string, } | { "type": "input_file", file_data: string | null, file_id: string | null, filename: string | null, } | { "type": "output_text", text: string, } | { "type": "url_file", url: string, filename: string | null, };
