// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when the agent calls `present_reading_view`.
 */
export type PresentDocumentEvent = { call_id: string, turn_id: string, document_id: string, title: string, content: string, };
