// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ATA: per-cron-job row in [`SchedulingTasksSnapshotEvent`]. Timestamps are
 * RFC 3339 strings (rather than i64) so the TUI can render them without
 * pulling in chrono on the wire.
 */
export type SchedulingCronRow = { task_id: string, cron_expr: string, prompt: string, status: string, fire_count: bigint, last_fired_at?: string | null, next_fire_at?: string | null, };
