// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ATA: a single streamed line from a running monitor command. The `stream`
 * field is `"stdout"` or `"stderr"`. Emitted per-line for live TUI display.
 * Not persisted to rollouts and never fed back to the LLM — see
 * [`EventMsg::SchedulingMonitorOutputDelta`].
 */
export type SchedulingMonitorOutputDeltaEvent = { task_id: string, stream: string, line: string, };
