// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ATA: per-monitor row in [`SchedulingTasksSnapshotEvent`].
 */
export type SchedulingMonitorRow = { task_id: string, command: string, status: string, lines_emitted: bigint, started_at?: string | null, stopped_at?: string | null, };
