// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ATA: per-loop row in [`SchedulingTasksSnapshotEvent`].
 */
export type SchedulingLoopRow = { task_id: string, prompt: string,
/**
 * Fixed-interval loops report their interval here in seconds; dynamic /
 * model-paced loops are `None`.
 */
interval_seconds?: number | null, status: string, iteration_count: bigint, last_iter_at?: string | null, next_wakeup_at?: string | null,
/**
 * Optional agent-supplied human-readable label.
 */
name?: string | null,
/**
 * Pre-formatted iteration history (newest last) for the detail view.
 */
recent_events?: Array<string>, };
