// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ATA: discriminator for the scheduling task families, used on the wire by
 * [`Op::DeleteSchedulingTask`] and any future per-kind operations.
 */
export type SchedulingTaskKind = "cron" | "monitor";
