// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchedulingCronRow } from "./SchedulingCronRow";
import type { SchedulingMonitorRow } from "./SchedulingMonitorRow";

/**
 * ATA: response payload for `Op::ListSchedulingTasks`. Always non-null —
 * when scheduling is disabled or no tasks exist, the lists are empty rather
 * than the whole event being omitted.
 */
export type SchedulingTasksSnapshotEvent = { cron_jobs: Array<SchedulingCronRow>, monitors: Array<SchedulingMonitorRow>,
/**
 * True iff `Feature::Scheduling` is enabled for the session. Lets the
 * TUI distinguish "scheduling off" from "scheduling on but no tasks".
 */
scheduling_enabled: boolean, };
