// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when the agent calls `update_document_section`.
 */
export type UpdateDocumentSectionEvent = { call_id: string, turn_id: string, document_id: string, section_index: number, content: string, };
