#!/usr/bin/env bash
#
# Aggregate the latest structured verdict per component into a status rollup.
#
# Each agentic run writes tests/tui/reports/<date>-<component>.verdict.json
# (see run-agentic.sh). This scans them, keeps the newest per component, and
# regenerates tests/tui/STATUS.md plus a printed table. Exit non-zero if any
# component's latest verdict is "fail".
#
# Usage: ./rollup.sh

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
CODEX_RS=$(cd "$SCRIPT_DIR/../.." && pwd)
cd "$CODEX_RS"

REPORTS_DIR="tests/tui/reports"
STATUS_MD="tests/tui/STATUS.md"

python3 - "$REPORTS_DIR" "$STATUS_MD" <<'PY'
import glob, json, os, sys

reports_dir, status_md = sys.argv[1], sys.argv[2]

# Latest verdict per component (verdict files sort lexically by ISO date prefix).
latest = {}
for path in sorted(glob.glob(os.path.join(reports_dir, "*.verdict.json"))):
    try:
        v = json.load(open(path))
    except Exception as e:
        print(f"warning: skipping unparseable verdict {path}: {e}", file=sys.stderr)
        continue
    comp = v.get("component") or os.path.basename(path).split(".verdict.json")[0]
    v["_path"] = path
    v["_mtime"] = os.path.getmtime(path)
    prev = latest.get(comp)
    if prev is None or v["_mtime"] >= prev["_mtime"]:
        latest[comp] = v

# Every spec, even ones never run, so coverage gaps are visible.
specs = sorted(
    os.path.basename(p)[:-3]
    for p in glob.glob("tests/tui/specs/*.md")
    if os.path.basename(p) not in ("BACKLOG.md",)
)

def counts(v):
    f = v.get("findings", []) or []
    return (
        sum(1 for x in f if x.get("severity") == "high"),
        sum(1 for x in f if x.get("severity") == "medium"),
        sum(1 for x in f if x.get("severity") == "low"),
    )

ICON = {"pass": "✅ pass", "partial": "🟡 partial", "fail": "❌ fail"}

rows = []
any_fail = False
n_pass = n_partial = n_fail = n_unrun = 0
for comp in specs:
    v = latest.get(comp)
    if v is None:
        rows.append((comp, "— not run", "—", 0, 0, 0, ""))
        n_unrun += 1
        continue
    verdict = str(v.get("verdict", "?")).lower()
    hi, md, lo = counts(v)
    date = ""
    base = os.path.basename(v["_path"])
    if len(base) >= 10 and base[:4].isdigit():
        date = base[:10]
    rows.append((comp, ICON.get(verdict, verdict), date, hi, md, lo, v.get("report", "")))
    if verdict == "fail":
        any_fail = True; n_fail += 1
    elif verdict == "partial":
        n_partial += 1
    elif verdict == "pass":
        n_pass += 1

lines = []
lines.append("# Agentic test status\n")
lines.append("Generated by `tests/tui/rollup.sh` from the latest "
             "`reports/*.verdict.json` per component. Do not edit by hand.\n")
lines.append(f"Summary: {n_pass} pass · {n_partial} partial · {n_fail} fail · "
             f"{n_unrun} not run (of {len(specs)} specs)\n")
lines.append("| Spec | Verdict | Date | High | Med | Low | Report |")
lines.append("|------|---------|------|-----:|----:|----:|--------|")
for comp, verdict, date, hi, md, lo, report in rows:
    rep = f"`{os.path.basename(report)}`" if report else ""
    lines.append(f"| {comp} | {verdict} | {date} | {hi} | {md} | {lo} | {rep} |")
out = "\n".join(lines) + "\n"

open(status_md, "w").write(out)
# Also print a compact view to the terminal.
print(out)
print(f"wrote {status_md}")
sys.exit(2 if any_fail else 0)
PY
